[project]
name = "costume-classifier"
version = "0.1.0"
description = "Doorstep costume classifier - Raspberry Pi edge computer vision system for Halloween"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.12.0.88",
    "python-dotenv>=1.1.1",
]
